services:
  db:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_DB: revisium-dev
      POSTGRES_USER: revisium
      POSTGRES_PASSWORD: password
  revisium:
    pull_policy: always
    depends_on:
      - db
    image: revisium/revisium:v2.0.0-alpha.1
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://revisium:password@db:5432/revisium-dev?schema=public
      #      METRICS_ENABLED: "true"
      #      GRACEFUL_SHUTDOWN_TIMEOUT: 10000
      #      FILE_PLUGIN_PUBLIC_ENDPOINT: 'https://...'
      #      S3_ENDPOINT: ''
      #      S3_REGION: ''
      #      S3_BUCKET: ''
      #      S3_ACCESS_KEY_ID: ''
      #      S3_SECRET_ACCESS_KEY: ''
      #      GRAPHQL_HIDE_NODE_TYPES: false
      #      GRAPHQL_HIDE_FLAT_TYPES: false
      #      GRAPHQL_FLAT_POSTFIX: "Flat"
      #      GRAPHQL_NODE_POSTFIX: ""
      #      GRAPHQL_PREFIX_FOR_TABLES: ""
      #      GRAPHQL_PREFIX_FOR_COMMON: ""